# Generated by Django 3.1.7 on 2021-02-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210227_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='detailed_description',
            field=models.TextField(max_length=3000),
        ),
    ]
