# Generated by Django 3.1.7 on 2021-03-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210305_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=34, max_length=2000),
            preserve_default=False,
        ),
    ]
