# Generated by Django 3.1.7 on 2021-03-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20210305_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='balance',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('other', 'Разное'), ('sports', 'Спортивне'), ('Classic', 'Классические'), ('For home', 'Для дома'), ('for study', 'Для учебы')], max_length=100),
        ),
    ]
